### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by scflode**
Fixed some typos and grammar.

### CODE REVIEW

**Comment by ndufreche** [comment]
:+1: Thanks a lot @scflode

**Comment by scflode** [comment]
You're welcome. Hope it helps.

**Comment by ndufreche** [comment]
With no doubt :)

**Comment by eric-chau** [comment]
Thank you @scflode for your contribution :+1: !

**Comment by mickaelandrieu** [comment]
@eric-chau deployed. Don't forget to deploy docs when you merge a pull request, or no one can enjoy the improvements ^^

**Pull request merged**
