### PR TITLE
Added Routing component

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by ndufreche** [comment]
You forgot to upgrade mkdocs.yml file

**Comment by mickaelandrieu** [comment]
@ndufreche nice catch @ndufreche, updated.

**Comment by ndufreche** [comment]
It's seems fine for me :+1:

**Comment by mickaelandrieu** [comment]
thank you for review @ndufreche.

When needed, we will update and complete this part.

**Pull request merged**
